---
- name: Enable cluster
  shell: >
    curl -X POST -H "Content-Type: application/json"
    http://{{user}}:{{password}}@{{master_node}}:5984/_cluster_setup
    -d '{"action": "enable_cluster", "bind_address":"0.0.0.0","username": "{{user}}", "password":"{{password}}", "port": "5984","remote_node": "{{target_node}}", "node_count": "{{node_count}}","remote_current_user":"{{user}}", "remote_current_password":"{{password}}"}'

- name: Add node
  shell: >
    curl -X POST -H "Content-Type: application/json"
    http://{{user}}:{{password}}@{{master_node}}:5984/_cluster_setup
    -d '{"action": "add_node", "host":"{{target_node}}","port": "5984", "username": "{{user}}", "password":"{{password}}"}'

- name: Finish cluster
  shell: >
    curl -X POST -H "Content-Type: application/json"
    http://{{user}}:{{password}}@{{master_node}}:5984/_cluster_setup
    -d '{"action": "finish_cluster"}'

# waiting cluster finish
- pause:
    minutes: 2
