# Common vars
availability_zone: melbourne-qh2-uom

# Volume
volumes:
  - vol_name: cccProject-vol-1-1
    vol_size: 20
  - vol_name: cccProject-vol-1-2
    vol_size: 20


# Security group
security_groups:
  - name: cccProject_ssh
    description: "Security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: cccProject_http
    description: "Security group for HTTP"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0

# Instance
instances:
  - name: cccProject-1
    volumes: ['cccProject-vol-1-1', 'cccProject-vol-1-2']


instance_image: 45225edb-66d8-4fd0-bf41-132a31a18166
instance_key_name: cccProject
instance_flavor: uom.mse.2c9g
