---
- name: Create Wordpress directory
  tags: 'wordpress'
  become: yes
  file:
    path: "{{ wp_dir }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    recurse: yes
    state: directory


- name: Configure compose
  tags: 'wordpress'
  become: yes
  template:
    src: docker-compose.yaml.j2
    dest: "{{ wp_dir }}/docker-compose.yaml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"


- name: just force systemd to reread configs (2.4 and above)
  become: yes
  systemd:
    state: restarted
    daemon_reload: yes
    name: docker

- name: Run docker compose
  tags: 'wordpress'
  become: yes
  docker_compose:
    project_src: "{{ wp_dir }}"
    pull: yes
    state: present
    remove_orphans: yes
    recreate: always
