---
volumes:
  - device: /dev/vdb
    mountpoint: /var/lib/docker
  - device: /dev/vdc
    mountpoint: /data

wp_dir: docker

target_node: 172.26.131.195
master_node: 172.26.133.166
user: admin
password: admin
node_count: 3
database:
  - database_name: tweet_json_1
  - database_name: test_db_gui
