---
- name: Enable maintanence mode
  shell: 'curl -X PUT -H "Content-type: application/json" \
    http://{{user}}:{{password}}@{{target_node}}:5984/_node/couchdb@{{target_node}}/_config/couchdb/maintenance_mode \
    -d "\"true\""'
  delegate_to: localhost

- name: Get metadata file from database
  shell: >
    curl http://{{user}}:{{password}}@{{master_node}}:5984/_node/_local/_dbs/{{item.database_name}} > metadata.json;
    python modifyMetadata.py -i metadata.json -o metadata_out.json -n couchdb@{{target_node}};
    metadata=$(<metadata_out.json);
    curl -X PUT http://{{user}}:{{password}}@{{master_node}}:5984/_node/_local/_dbs/{{item.database_name}} -d "${metadata}"
  delegate_to: localhost
  loop: '{{database}}'


#- pause:
#    seconds: 1

#- name: Modify metatadata file
#  shell: "python modifyMetadata.py -i metadata.json -o metadata_out.json -n couchdb@{{target_node}}"
#  delegate_to: localhost

#- name: Updating cluster metadata of database
#  shell: 'metadata=$(<metadata_out.json); \
#  curl -X PUT http://{{user}}:{{password}}@{{master_node}}:5984/_node/_local/_dbs/{{database_name}} -d "${metadata}"'
#  delegate_to: localhost

- name: Forcing synchronization of the shards
  shell: 'curl -X POST http://{{user}}:{{password}}@{{master_node}}:5984/{{item.database_name}}/_sync_shards'
  delegate_to: localhost
  loop: '{{database}}'

# wait shards being synchronized
- pause:
    minutes: 3

- name: Clear the maintanence mode
  shell: 'curl -X PUT -H "Content-type: application/json" \
    http://{{user}}:{{password}}@{{target_node}}:5984/_node/couchdb@{{target_node}}/_config/couchdb/maintenance_mode \
    -d "\"false\""'
  delegate_to: localhost
