---

- name: Run harvester in docker
  become: yes
  docker_container:
    name: "{{item.keyword}}-harvester"
    image: whyneedaname/tweets-harvester:latest
    auto_remove: yes
    command: -q {{item.keyword}} -db one_hundred_percent_deadlocked_not_gonna_changed_name_database
  loop: '{{keywords}}'
